<Firebase Project for each flavor and flavor configuration>
hkarmoush/flutter_starter pull request #11
Opened 2023-09-17 16:14 UTC by Odaykhz

2023-09-17 17:54 UTC, hkarmoush commented
.dart tools folder should no show in the commit, it should be added to gitignore to be ignored by git

2023-09-17 17:54 UTC, hkarmoush commented on .flutter-plugins
> +# This is a generated file; do not edit or check into version control.
This should be ignored too

2023-09-17 17:54 UTC, hkarmoush commented on .flutter-plugins-dependencies
> +{"info":"This is a generated file; do not edit or check into version control.","plugins":{"ios":[{"name":"firebase_core","path":"/Users/odaykhazaeleh/.pub-cache/hosted/pub.dev/firebase_core-2.15.1/",
This should be ignored too

2023-09-17 17:55 UTC, hkarmoush commented on build/flutter_assets/AssetManifest.json
> +{}
build folder should be ignored too

2023-09-17 17:55 UTC, hkarmoush commented on ios/Podfile
> +# platform :ios, '11.0'
Let's enable for iOS 13

2023-09-17 17:56 UTC, hkarmoush commented on lib/firebase_options_dev.dart
> +// File generated by FlutterFire CLI.
hmmmm,

2023-09-17 17:56 UTC, hkarmoush commented on lib/main_production.dart
> +  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
How are you selecting which Firebase project here?

2023-09-17 17:56 UTC, hkarmoush commented on lib/main_staging.dart
> +  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
How are you selecting which Firebase project here?

2023-09-17 17:57 UTC, hkarmoush commented on lib/main_staging.dart
> +  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
How are you selecting which Firebase project here?

2023-09-17 17:57 UTC, hkarmoush commented on pubspec.lock
>        url: "https://pub.dev"
this should be ignored too

2023-09-17 17:57 UTC, hkarmoush commented on windows/flutter/generated_plugin_registrant.cc
remove windows target

2023-09-18 15:19 UTC, Odaykhz commented on lib/main_staging.dart
> +  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
each firebase project has a firebase_options file for each dev, stg and prod.

2023-09-18 15:19 UTC, Odaykhz commented on lib/main_staging.dart
> +  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
each firebase project has a firebase_options file for each dev, stg and prod.

2023-09-19 20:08 UTC, hkarmoush commented on windows/flutter/generated_plugin_registrant.cc
@Odaykhz bump

2023-09-19 20:08 UTC, hkarmoush commented on pubspec.lock
>        url: "https://pub.dev"
@Odaykhz bump

2023-09-19 20:08 UTC, hkarmoush commented on build/flutter_assets/AssetManifest.json
> +{}
@Odaykhz bump

2023-09-19 20:09 UTC, hkarmoush commented on .flutter-plugins-dependencies
> +{"info":"This is a generated file; do not edit or check into version control.","plugins":{"ios":[{"name":"firebase_core","path":"/Users/odaykhazaeleh/.pub-cache/hosted/pub.dev/firebase_core-2.15.1/",
@Odaykhz bump

2023-09-19 20:09 UTC, hkarmoush commented on .flutter-plugins
> +# This is a generated file; do not edit or check into version control.
@Odaykhz bump

2023-09-19 20:16 UTC, hkarmoush requested changes
review the remaining comments please, good job though

2023-09-19 20:43 UTC, hkarmoush commented on lib/main_staging.dart
> +  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
Well, You're not passing it yet correctly?

2023-09-19 20:44 UTC, hkarmoush commented on lib/main_staging.dart
> +  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
Ooooh I see, gg


do they run correctly?

2023-09-19 20:47 UTC, Odaykhz commented on lib/main_staging.dart
> +  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
yeah they are good

2023-09-22 22:27 UTC, hkarmoush approved these changes

2023-09-22 22:27 UTC, merged